services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=study-auth
    volumes:
      - pg_data:/bitnami/postgresql
    ports:
      - "5432:5432"

volumes:
  pg_data: